const old_edges = [
    {
      id: '1-2',
      source: '1',
      target: '2',
      animated: true,
      style: { stroke: '#fff' },
    },
    {
      id: '2-3',
      source: '2',
      target: '3',
      sourceHandle: 'a',
      animated: true,
      style: { stroke: '#fff' },
    },
    {
      id: '2-4',
      source: '2',
      target: '4',
      sourceHandle: 'b',
      animated: true,
      style: { stroke: '#fff' },
    },
    {
      id: '3-5',
      source: '3',
      target: '5',
      sourceHandle: 'a',
      animated: true,
      style: { stroke: '#fff' },
    },
    {
      id: '3-6',
      source: '3',
      target: '6',
      sourceHandle: 'b',
      animated: true,
      style: { stroke: '#fff' },
    },
    {
      id: '4-7',
      source: '4',
      target: '7',
      sourceHandle: 'a',
      animated: true,
      style: { stroke: '#fff' },
    },
    {
      id: '5-8',
      source: '5',
      target: '8',
      sourceHandle: 'a',
      animated: true,
      style: { stroke: '#fff' },
    },
    {
      id: '6-8',
      source: '6',
      target: '8',
      sourceHandle: 'b',
      animated: true,
      style: { stroke: '#fff' },
    },
    {
      id: '7-8',
      source: '7',
      target: '8',
      sourceHandle: 'a',
      animated: true,
      style: { stroke: '#fff' },
    },
  ]